Traceback (most recent call last):
  File "C:\Users\kamac\miniconda3\envs\data_viz\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\kamac\miniconda3\envs\data_viz\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\kamac\miniconda3\envs\data_viz\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\kamac\miniconda3\envs\data_viz\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\kamac\miniconda3\envs\data_viz\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\kamac\miniconda3\envs\data_viz\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\kamac\miniconda3\envs\data_viz\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
columnas_ordenadas = [
    'Nombre_Departamento', 'Nombre_Municipio', 'sitio_def', 'aÃ±o_def', 
    'mes_def', 'sexo', 'estado_civil', 'grupo_edad', 'nivel_edu', 'grupo_etnico','rec_etnico',
    'depto_res', 'seg_social', 'ent_salud_cod', 'prob_muerte', 'cert_medica', 'asistencia_med',
    'causa_directa', 'causa_ant_1', 'causa_ant_2', 'causa_basica', 'causa_OPS', 'region', 'depto_ocurr', 'municipio'
]
data_analisis = data[columnas_ordenadas]
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mKeyError[0m                                  Traceback (most recent call last)
Cell [1;32mIn[56], line 7[0m
[0;32m      1[0m columnas_ordenadas [38;5;241m=[39m [
[0;32m      2[0m     [38;5;124m'[39m[38;5;124mNombre_Departamento[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mNombre_Municipio[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124msitio_def[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124maÃ±o_def[39m[38;5;124m'[39m, 
[0;32m      3[0m     [38;5;124m'[39m[38;5;124mmes_def[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124msexo[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mestado_civil[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mgrupo_edad[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mnivel_edu[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mgrupo_etnico[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mrec_etnico[39m[38;5;124m'[39m,
[0;32m      4[0m     [38;5;124m'[39m[38;5;124mdepto_res[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mseg_social[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124ment_salud_cod[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mprob_muerte[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mcert_medica[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124masistencia_med[39m[38;5;124m'[39m,
[0;32m      5[0m     [38;5;124m'[39m[38;5;124mcausa_directa[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mcausa_ant_1[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mcausa_ant_2[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mcausa_basica[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mcausa_OPS[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mregion[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mdepto_ocurr[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mmunicipio[39m[38;5;124m'[39m
[0;32m      6[0m ]
[1;32m----> 7[0m data_analisis [38;5;241m=[39m [43mdata[49m[43m[[49m[43mcolumnas_ordenadas[49m[43m][49m

File [1;32m~\miniconda3\envs\data_viz\lib\site-packages\pandas\core\frame.py:4108[0m, in [0;36mDataFrame.__getitem__[1;34m(self, key)[0m
[0;32m   4106[0m     [38;5;28;01mif[39;00m is_iterator(key):
[0;32m   4107[0m         key [38;5;241m=[39m [38;5;28mlist[39m(key)
[1;32m-> 4108[0m     indexer [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcolumns[49m[38;5;241;43m.[39;49m[43m_get_indexer_strict[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mcolumns[39;49m[38;5;124;43m"[39;49m[43m)[49m[[38;5;241m1[39m]
[0;32m   4110[0m [38;5;66;03m# take() does not accept boolean indexers[39;00m
[0;32m   4111[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(indexer, [38;5;124m"[39m[38;5;124mdtype[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m) [38;5;241m==[39m [38;5;28mbool[39m:

File [1;32m~\miniconda3\envs\data_viz\lib\site-packages\pandas\core\indexes\base.py:6200[0m, in [0;36mIndex._get_indexer_strict[1;34m(self, key, axis_name)[0m
[0;32m   6197[0m [38;5;28;01melse[39;00m:
[0;32m   6198[0m     keyarr, indexer, new_indexer [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_reindex_non_unique(keyarr)
[1;32m-> 6200[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_raise_if_missing[49m[43m([49m[43mkeyarr[49m[43m,[49m[43m [49m[43mindexer[49m[43m,[49m[43m [49m[43maxis_name[49m[43m)[49m
[0;32m   6202[0m keyarr [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mtake(indexer)
[0;32m   6203[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(key, Index):
[0;32m   6204[0m     [38;5;66;03m# GH 42790 - Preserve name from an Index[39;00m

File [1;32m~\miniconda3\envs\data_viz\lib\site-packages\pandas\core\indexes\base.py:6252[0m, in [0;36mIndex._raise_if_missing[1;34m(self, key, indexer, axis_name)[0m
[0;32m   6249[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNone of [[39m[38;5;132;01m{[39;00mkey[38;5;132;01m}[39;00m[38;5;124m] are in the [[39m[38;5;132;01m{[39;00maxis_name[38;5;132;01m}[39;00m[38;5;124m][39m[38;5;124m"[39m)
[0;32m   6251[0m not_found [38;5;241m=[39m [38;5;28mlist[39m(ensure_index(key)[missing_mask[38;5;241m.[39mnonzero()[[38;5;241m0[39m]][38;5;241m.[39munique())
[1;32m-> 6252[0m [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mnot_found[38;5;132;01m}[39;00m[38;5;124m not in index[39m[38;5;124m"[39m)

[1;31mKeyError[0m: "['depto_ocurr', 'municipio'] not in index"

